# Generated by Django 4.1.7 on 2023-03-28 15:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[A-Za-z][A-Za-z0-9_-]{1,13}[A-Za-z0-9]$', message='Incorrect expression of login.')])),
                ('nickname', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^[a-zA-Z]\\w*$', message='Incorrect expression of nickname.')])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,30}$', message='Incorrect expression of password.')])),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.RegexValidator('^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,4}$', message='Incorrect expression of e-mail.')])),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField(auto_now=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(30, django.core.validators.MaxLengthValidator(10000))])),
                ('image', models.ImageField(null=True, upload_to='posts')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='Blog.user')),
                ('tags', models.ManyToManyField(to='Blog.tag')),
            ],
        ),
    ]
