# Generated by Django 4.2.1 on 2024-02-28 22:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_alter_author_description_alter_author_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]\\w{2,}$', message='Incorrect expression of nickname.')]),
        ),
    ]
